bgaebalja/bsherpa-backend

- src/main/resources/application.yml
> [#2] AWS RDS 서비스 적용

- src/main/resources/application.yml
> [#6] 배포 서버에 SSL/TLS 인증 적용

- .dockerignore
- Dockerfile
- Jenkinsfile
- docker-compose.yml
- Jenkinsfile
- Dockerfile
- .dockerignore
- docker-compose.yml
> [#4] CI/CD 파이프라인 구축

- Jenkinsfile
- docker-compose.yml
- src/main/java/bgaebalja/bsherpa/configuration/DataSourceConfig.java
- src/main/java/bgaebalja/bsherpa/configuration/TransactionConfig.java
- src/main/java/bgaebalja/bsherpa/datasource/CustomRoutingDataSource.java
- src/main/java/bgaebalja/bsherpa/datasource/DatabaseType.java
- src/main/resources/application.yml
- DataSourceConfig
- TransactionConfig
- CustomRoutingDataSource
- DatabaseType
- application.yml
- Jenkinsfile
- docker-compose.yml
> [#5] 데이터베이스 분산 처리를 위한 라우팅 설정

- src/main/java/bgaebalja/bsherpa/BsherpaApplication.java
> [#10] 스프링 시큐리티 자동 설정 적용 해제

- src/main/java/bgaebalja/bsherpa/aop/LoggingAspect.java
- src/main/java/bgaebalja/bsherpa/configuration/InterceptorConfig.java
- src/main/java/bgaebalja/bsherpa/interception/LoggingInterceptor.java
- src/main/java/bgaebalja/bsherpa/util/LogConstant.java
- src/main/java/bgaebalja/bsherpa/util/PerformanceMeasurer.java
- src/main/resources/logback-spring.xml
- logback-spring.xml
- 애플리케이션 설정 추가
- 전체 Controller Components의 요청과 응답 로깅
- 시간 성능 측정
- 메모리 성능 측정
- 전체 Service Components의 작업 수행 로깅
- 시간 성능 측정
- 메모리 성능 측정
> [#12] 전체 프로젝트의 로깅 프로세스 추가

- build.gradle
> [#4] 프로젝트 이름과 버전을 추출하는 설정 추가

- Jenkinsfile
- docker-compose.yml
- src/main/java/bgaebalja/bsherpa/configuration/S3Config.java
- src/main/resources/application.yml
- S3Config 클래스
- AWS Access key
- AWS Secret key
- AWS 지역 설정
- AWS S3 버킷 이름
- Jenkins Credentials에 환경변수
- Jenkinsfile
- docker-compose.yml
> [#16] AWS S3 서비스 적용

- src/main/resources/application.yml
- application.yml의 AWS RDS 환경변수명
> [#18] 배포 서버의 애플리케이션 컨테이너에서 RDS endpoint 환경변수를 찾지 못하는 문제 해결

- src/main/java/bgaebalja/bsherpa/util/EntityConstant.java
> [#14] 누락된 EntityConstant 클래스 추가

- src/main/java/bgaebalja/bsherpa/exception/ErrorResponse.java
- src/main/java/bgaebalja/bsherpa/exception/ExceptionMessage.java
- src/main/java/bgaebalja/bsherpa/exception/GlobalExceptionHandler.java
- src/main/java/bgaebalja/bsherpa/exception/IdNoValueException.java
- src/main/java/bgaebalja/bsherpa/exception/InvalidIdException.java
- src/main/java/bgaebalja/bsherpa/exception/InvalidValueException.java
- src/main/java/bgaebalja/bsherpa/exception/NoValueException.java
- src/main/java/bgaebalja/bsherpa/exception/ParsingBooleanException.java
- src/main/java/bgaebalja/bsherpa/exception/ParsingFloatException.java
- src/main/java/bgaebalja/bsherpa/exception/ParsingIntegerException.java
- src/main/java/bgaebalja/bsherpa/exception/ParsingLocalDateTimeException.java
- src/main/java/bgaebalja/bsherpa/exception/ParsingLongException.java
- src/main/java/bgaebalja/bsherpa/exception/ParsingShortException.java
- src/main/java/bgaebalja/bsherpa/exception/TokenNoValueException.java
- Exception Handler
- 주로 발생하는 공통 예외 처리
- 에러 코드
- 에러 메시지
- 공통 커스텀 예외들
- 공통 커스텀 예외 메시지
> [#23] 공통 예외 처리를 위한 Exception Handler 추가

- build.gradle
- src/main/java/bgaebalja/bsherpa/configuration/SwaggerConfig.java
- springfox 의존성
- SwaggerConfig 클래스
> [#24] 서버 API 문서화를 위한 Swagger 설정 추가

- src/main/java/bgaebalja/bsherpa/util/FormatConverter.java
- src/main/java/bgaebalja/bsherpa/util/FormatValidator.java
- src/main/java/bgaebalja/bsherpa/util/RegularExpressionConstant.java
> [#30] 포맷 검증을 위한 FormatValidator 클래스, 포맷 변환을 위한 FormatConverter 클래스 추가

- src/main/java/bgaebalja/bsherpa/util/RequestConstant.java
> [#24, #29] 누락된 RequestConstant 클래스 추가

- src/main/java/bgaebalja/bsherpa/configuration/WebSecurityConfig.java
> [#34] DI Container에 HttpSecurity 빈이 등록되지 않는 문제 해결

- src/main/java/bgaebalja/bsherpa/client/chapter/ChapterApiClient.java
- src/main/java/bgaebalja/bsherpa/client/chapter/ChapterApiResponse.java
- src/main/java/bgaebalja/bsherpa/client/exam/ExamApiClient.java
- src/main/java/bgaebalja/bsherpa/client/exam/ExamApiResponse.java
- src/main/java/bgaebalja/bsherpa/client/item/ItemApiClient.java
- src/main/java/bgaebalja/bsherpa/client/item/ItemApiResponse.java
- src/main/java/bgaebalja/bsherpa/client/itemimage/ItemImageApiClient.java
- src/main/java/bgaebalja/bsherpa/client/itemimage/ItemImageApiResponse.java
- src/main/java/bgaebalja/bsherpa/question/controller/QuestionController.java
- src/main/java/bgaebalja/bsherpa/question/domain/GetQuestionResponse.java
- src/main/java/bgaebalja/bsherpa/question/domain/Question.java
- src/main/java/bgaebalja/bsherpa/question/repository/QuestionRepository.java
- src/main/java/bgaebalja/bsherpa/question/service/QuestionService.java
- src/main/java/bgaebalja/bsherpa/question/service/QuestionServiceImpl.java
- chapter
- exam
-  item
- itemimage
- controller
- service
- domain
- repository
> [#25] 기본 프로젝트 구조 생성

- src/main/java/bgaebalja/bsherpa/configuration/WebSecurityConfig.java
> [#37] 모든 요청에 대한 보안 적용 해제

- build.gradle
- src/main/java/bgaebalja/bsherpa/client/item/ItemApiResponse.java
- src/main/java/bgaebalja/bsherpa/collection/domain/Collection.java
- src/main/java/bgaebalja/bsherpa/configuration/S3Config.java
- src/main/java/bgaebalja/bsherpa/configuration/WebSecurityConfig.java
- src/main/java/bgaebalja/bsherpa/question/controller/QuestionController.java
- src/main/java/bgaebalja/bsherpa/question/domain/CreateQuestionRequest.java
- src/main/java/bgaebalja/bsherpa/question/domain/Difficulty.java
- src/main/java/bgaebalja/bsherpa/question/domain/GetQuestionResponse.java
- src/main/java/bgaebalja/bsherpa/question/domain/Question.java
- src/main/java/bgaebalja/bsherpa/question/domain/QuestionType.java
- src/main/java/bgaebalja/bsherpa/question/exception/DifficultyNotFoundException.java
- src/main/java/bgaebalja/bsherpa/question/exception/ExceptionMessage.java
- src/main/java/bgaebalja/bsherpa/question/exception/QuestionTypeNotFoundException.java
- src/main/java/bgaebalja/bsherpa/question/service/QuestionService.java
- src/main/java/bgaebalja/bsherpa/question/service/QuestionServiceImpl.java
- src/main/java/bgaebalja/bsherpa/util/QuestionClassifier.java
- src/main/java/bgaebalja/bsherpa/util/ResponseGenerator.java
- 문제 등록 요청
- 문제 등록 비즈니스 로직
- 문제 데이터 저장
- 201 status code 응답
> [#43] 문제 등록 기능 추가

- src/main/java/bgaebalja/bsherpa/question/domain/Question.java
- src/main/java/bgaebalja/bsherpa/question/domain/QuestionType.java
- src/main/java/bgaebalja/bsherpa/util/QuestionClassifier.java
- 자유선지형
- 2지 선택
- 3지 선택
- 4지 선택
- 5지 선택
- 단답 유순형
- 단답 무순형
- 단답 그룹형
- 논술형
- 선택채움형
- 서술형
- 드래그 드랍
- 영역 선택형
- 선잇기형
- 기타
> [#45] 문제 유형 추가

- src/main/java/bgaebalja/bsherpa/book/controller/BookController.java
- src/main/java/bgaebalja/bsherpa/book/domain/Book.java
- src/main/java/bgaebalja/bsherpa/book/domain/BookResponse.java
- src/main/java/bgaebalja/bsherpa/book/repository/BookRepository.java
- src/main/java/bgaebalja/bsherpa/book/service/BookService.java
- src/main/java/bgaebalja/bsherpa/book/service/BookServiceImpl.java
- 교재
- domain
- repository
- service
- controller
> feat(book): 교재 도메인 기능 추가

- src/main/java/bgaebalja/bsherpa/user/Users.java
> feat(user): 회원 도메인 추가

- src/main/java/bgaebalja/bsherpa/user/domain/Users.java
- src/main/java/bgaebalja/bsherpa/user/repository/UserRepository.java
- 회원
- repository 추가
- domain 생성
- 도메인에 users 넣음
> feat(user): 회원 레포지토리 추가 및 user domain package 생성

- build.gradle
- src/main/java/bgaebalja/bsherpa/exception/JwtCustomException.java
- src/main/java/bgaebalja/bsherpa/security/filter/JwtCheckFilter.java
- src/main/java/bgaebalja/bsherpa/security/handler/CustomAccessDeniedHandler.java
- src/main/java/bgaebalja/bsherpa/security/handler/LoginFailureHandler.java
- src/main/java/bgaebalja/bsherpa/security/handler/LoginSuccessHandler.java
- src/main/java/bgaebalja/bsherpa/user/domain/UserDTO.java
- src/main/java/bgaebalja/bsherpa/user/service/UserDetailsServiceImpl.java
- src/main/java/bgaebalja/bsherpa/util/JwtUtil.java
- 유저 인증
- Jwt
- security
- Gson 추가
> feat(user): 유저 인증 관련 기능 추가 및 Gson 추가

- src/main/java/bgaebalja/bsherpa/configuration/SecurityConfig.java
- src/main/java/bgaebalja/bsherpa/util/JwtUtil.java
> feat(user): security 설정 추가

- src/main/java/bgaebalja/bsherpa/security/filter/JwtCheckFilter.java
- security filter
- books 경로 필터 해제
> refactor(user): security filter 수정

- src/main/java/bgaebalja/bsherpa/security/filter/JwtCheckFilter.java
> feat(user): swagger 관련 필터 해제

- src/main/java/bgaebalja/bsherpa/book/controller/BookController.java
- book 컨트롤러 수정
- 리턴 배열에서 객체로 감싸서 반환
> refactor(book): 배열을 객체로 감싸서 반환

- src/main/java/bgaebalja/bsherpa/book/controller/BookController.java
- src/main/java/bgaebalja/bsherpa/security/handler/LoginSuccessHandler.java
- jwt 토큰 만료기간 타입 변경 메서드 리팩터링
- FormatConverter 의 parseToInt 사용
> refactor(security): jwt 토큰 만료기간 타입 변경 메서드 리팩터링

- src/main/java/bgaebalja/bsherpa/user/controller/RefreshController.java
- src/main/java/bgaebalja/bsherpa/user/controller/UserController.java
- src/main/java/bgaebalja/bsherpa/user/domain/UserJoinRequest.java
- src/main/java/bgaebalja/bsherpa/user/domain/Users.java
- src/main/java/bgaebalja/bsherpa/user/repository/UserRepository.java
- src/main/java/bgaebalja/bsherpa/user/service/UserDetailsServiceImpl.java
- src/main/java/bgaebalja/bsherpa/user/service/UserService.java
- src/main/java/bgaebalja/bsherpa/user/service/UserServiceImpl.java
> feat(user): 회원 로그인 및 회원가입 기능 추가

- Jenkinsfile
> [#62, #63] Jenkinsfile의 누락된 쉼표 추가

- Jenkinsfile
> [#65, #66] fix(CI/CD): Jenkinsfile의 누락된 쉼표 추가

- src/main/java/bgaebalja/bsherpa/user/controller/RefreshController.java
- src/main/java/bgaebalja/bsherpa/user/controller/UserController.java
- src/main/java/bgaebalja/bsherpa/user/domain/UserJoinRequest.java
- src/main/java/bgaebalja/bsherpa/user/domain/Users.java
- src/main/java/bgaebalja/bsherpa/user/repository/UserRepository.java
- src/main/java/bgaebalja/bsherpa/user/service/UserDetailsServiceImpl.java
- src/main/java/bgaebalja/bsherpa/user/service/UserService.java
- src/main/java/bgaebalja/bsherpa/user/service/UserServiceImpl.java
- controller
- domain
- service
> [#69] 삭제된 회원 관련 클래스 복구

- src/main/java/bgaebalja/bsherpa/book/domain/Book.java
- src/main/java/bgaebalja/bsherpa/book/domain/BookResponse.java
- src/main/java/bgaebalja/bsherpa/clazz/domain/Clazz.java
- src/main/java/bgaebalja/bsherpa/subject/domain/Subject.java
- 교재 관련 도메인
- 교재 도메인 수정
- 저자 추가
- bookName -> name 변경
- 등급 도메인 추가
- 과목 도메인 추가
> feat(book): 교재 관련 도메인 추가 및 수정

- src/main/java/bgaebalja/bsherpa/book/domain/BookResponse.java
> refactor(user): BookResponse API 값 수정

- src/main/java/bgaebalja/bsherpa/configuration/SecurityConfig.java
> fix(user): 시큐리티 filterChain 추가

- src/main/java/bgaebalja/bsherpa/configuration/SecurityConfig.java
- src/main/java/bgaebalja/bsherpa/configuration/WebSecurityConfig.java
- filterChain 중복 문제 해결
- WebSecurityConfig 주석 처리
> fix(user): 시큐리티 filterChain 중복 문제 해결

- src/main/java/bgaebalja/bsherpa/configuration/SecurityConfig.java
- src/main/java/bgaebalja/bsherpa/user/domain/Users.java
- src/main/java/bgaebalja/bsherpa/user/repository/UserRepository.java
- src/main/java/bgaebalja/bsherpa/user/service/UserDetailsServiceImpl.java
- 시큐리티 cors 설정
- "*" 로 변경
- 도메인
- email -> userId 로 변경
> feat(user): 시큐리티 cors 수정, 도메인 수정

- src/main/java/bgaebalja/bsherpa/configuration/SecurityConfig.java
> fix(user): 시큐리티 설정 cors 추가

- src/main/java/bgaebalja/bsherpa/configuration/SecurityConfig.java
- cors 설정 method 변경
- setAllowedOriginPatterns -> setAllowedOrigins
> refactor(user): 시큐리티 cors 설정 method 변경

- src/main/java/bgaebalja/bsherpa/exam/controller/ExamExternalController.java
> [#105] T셀파의 시험지 문항분류표 미리보기를 조회하는 엔드포인트의 Swagger 문서 문구 수정

- src/main/java/bgaebalja/bsherpa/client/item/GetChapterItemsRequest.java
> [#107] T셀파의 단원 별 문제 목록을 조회하는 엔드포인트 요청 DTO의 Swagger 문서 문구 수정

- src/main/java/bgaebalja/bsherpa/user/domain/Users.java
- user-role 이름 변경 및 컬럼 변경
- user-roles -> user-role
- user-role을 entity로서 구현하지 않았기 때문에 auditing 제거
> fix(user-role): 데이터베이스와 맞지 않는 부분 수정

- build.gradle
- src/main/java/bgaebalja/bsherpa/aop/Validator.java
- src/main/java/bgaebalja/bsherpa/user/controller/UserController.java
- src/main/java/bgaebalja/bsherpa/user/domain/UserJoinRequest.java
- src/main/java/bgaebalja/bsherpa/validation/CustomValid.java
- src/main/java/bgaebalja/bsherpa/validation/CustomValidField.java
- src/main/java/bgaebalja/bsherpa/validation/CustomValidation.java
- src/main/java/bgaebalja/bsherpa/validation/SchemaInitializer.java
- src/main/java/bgaebalja/bsherpa/validation/Valid.java
- src/main/resources/validate/join.json
> feat(user): 회원가입 유효성 검사 기능 추가

- src/main/java/bgaebalja/bsherpa/validation/Valid.java
> refactor(user): 안 쓰는 프로퍼티 제거

- src/main/resources/validate/join.json
> fix(user): join.json 수정

- src/main/java/bgaebalja/bsherpa/user/controller/SocialController.java
- src/main/java/bgaebalja/bsherpa/user/repository/UserRepository.java
- src/main/java/bgaebalja/bsherpa/user/service/UserService.java
- src/main/java/bgaebalja/bsherpa/user/service/UserServiceImpl.java
> feat(user): 소셜로그인 기능 추가(카카오)

- src/main/java/bgaebalja/bsherpa/collection/domain/Collection.java
> fix : Collection

- src/main/java/bgaebalja/bsherpa/client/itemimage/GetItemImagesResponse.java
- src/main/java/bgaebalja/bsherpa/exam/controller/ExamExternalController.java
- src/main/java/bgaebalja/bsherpa/question/controller/QuestionExternalController.java
- src/main/java/bgaebalja/bsherpa/question/controller/QuestionImageExternalController.java
- QuestionImageExternalController 클래스
- GetItemImagesResponse 클래스
> [#132] T셀파 API를 통해 단원 별 문제 이미지 검색 시 난이도 별 개수를 조정해서 반환하는 기능 추가

- src/main/java/bgaebalja/bsherpa/security/filter/JwtCheckFilter.java
- src/main/java/bgaebalja/bsherpa/user/controller/RefreshController.java
- src/main/java/bgaebalja/bsherpa/user/dto/request/RefreshRequest.java
- jwt-filter 적용
- 유저, books 제외
> fix(jwt-filter): 유저와 books를 제외한 나머지 필터 적용

- src/main/java/bgaebalja/bsherpa/security/filter/JwtCheckFilter.java
- src/main/java/bgaebalja/bsherpa/user/controller/UserController.java
- src/main/java/bgaebalja/bsherpa/user/domain/UserDTO.java
- src/main/java/bgaebalja/bsherpa/user/domain/UserJoinRequest.java
- src/main/java/bgaebalja/bsherpa/user/domain/Users.java
- src/main/java/bgaebalja/bsherpa/user/service/UserDetailsServiceImpl.java
- src/main/java/bgaebalja/bsherpa/user/service/UserService.java
- src/main/java/bgaebalja/bsherpa/user/service/UserServiceImpl.java
> feat(user): 회원 학생 롤 추가

- src/main/java/bgaebalja/bsherpa/security/filter/JwtCheckFilter.java
> refactor(user): UserDto 인스턴스 명 변경

- src/main/java/bgaebalja/bsherpa/collection/domain/Collection.java
- src/main/java/bgaebalja/bsherpa/collection/domain/GetCollectionResponse.java
- src/main/java/bgaebalja/bsherpa/collection/domain/GetCollectionsResponse.java
- src/main/java/bgaebalja/bsherpa/exam/controller/ExamController.java
- src/main/java/bgaebalja/bsherpa/exam/domain/Exam.java
- src/main/java/bgaebalja/bsherpa/exam/domain/GetExamResponse.java
- src/main/java/bgaebalja/bsherpa/exam/domain/GetExamsResponse.java
- src/main/java/bgaebalja/bsherpa/exam/exception/ExamNotFoundException.java
- src/main/java/bgaebalja/bsherpa/exam/exception/ExceptionMessage.java
- src/main/java/bgaebalja/bsherpa/exam/repository/ExamRepository.java
- src/main/java/bgaebalja/bsherpa/exam/service/ExamService.java
- src/main/java/bgaebalja/bsherpa/exam/service/ExamServiceImpl.java
- src/main/java/bgaebalja/bsherpa/passage/domain/GetPassageResponse.java
- src/main/java/bgaebalja/bsherpa/passage/domain/GetPassagesResponse.java
- src/main/java/bgaebalja/bsherpa/question/domain/GetQuestionResponse.java
- src/main/java/bgaebalja/bsherpa/question/domain/GetQuestionsResponse.java
- Exam
- GetExamsResponse
- GetExamResponse
- ExamService
- ExamServiceImpl
- ExamRepository
- ExamNotFoundException
- ExceptionMessage
- Collection
- GetCollectionsResponse
- GetCollectionResponse
- GetPassagesResponse
- GetPassageResponse
- GetQuestionsResponse
- GetQuestionResponse
- ExceptionMessage
> [#138] 시험지 목록을 받아오는 기능 추가

- src/main/java/bgaebalja/bsherpa/exam/controller/ExamController.java
- 시험지 정보 요청, 200 status code 응답
> [#140] 시험지 정보를 받아오는 기능 추가

- src/main/java/bgaebalja/bsherpa/user/controller/UserController.java
- src/main/java/bgaebalja/bsherpa/user/dto/request/UserSwaggerLoginRequest.java
- src/main/java/bgaebalja/bsherpa/user/dto/response/UserSwaggerLoginResponse.java
- src/main/java/bgaebalja/bsherpa/user/service/UserService.java
- src/main/java/bgaebalja/bsherpa/user/service/UserServiceImpl.java
> feat(user): 스웨거 확인용 기능 추가

- src/main/java/bgaebalja/bsherpa/exam/service/ExamServiceImpl.java
- src/main/java/bgaebalja/bsherpa/option/domain/GetOptionResponse.java
- src/main/java/bgaebalja/bsherpa/option/domain/GetOptionsResponse.java
- src/main/java/bgaebalja/bsherpa/option/domain/Option.java
- src/main/java/bgaebalja/bsherpa/question/domain/GetQuestionResponse.java
- src/main/java/bgaebalja/bsherpa/question/domain/Question.java
- src/main/java/bgaebalja/bsherpa/question/domain/QuestionType.java
- Option
- GetOptionsResponse
- GetOptionResponse
> [#144] 문제풀이 페이지에 보기 목록을 받아오는 기능 추가

- src/main/java/bgaebalja/bsherpa/user/controller/UserController.java
- src/main/java/bgaebalja/bsherpa/user/dto/request/UserSwaggerLoginRequest.java
- UserController 클래스
- UserSwaggerLoginRequestion 클래스
> [#146] 로그인 엔드포인트의 swagger 문서와 예시 추가

- src/main/java/bgaebalja/bsherpa/user/dto/request/UserSwaggerLoginRequest.java
> [#146, #147] swagger 예시 오타 수정

- src/main/java/bgaebalja/bsherpa/question/domain/GetQuestionResponse.java
- 시험지 조회 요청 엔드포인트의 응답값에서 Collection 클래스 제외
> [#151] Step4에서 시험지 JSON 데이터를 JS 객체로 파싱하지 못하는 문제 해결

- src/main/java/bgaebalja/bsherpa/option/domain/Option.java
> fix: Option

- src/main/java/bgaebalja/bsherpa/exam/controller/ExamController.java
> [#155, #156] 시험지 목록 조회 기능 요청 파라미터에 과목명 기본값 추가

- src/main/java/bgaebalja/bsherpa/question/repository/QuestionRepository.java
- src/main/java/bgaebalja/bsherpa/question/service/QuestionServiceImpl.java
> [#160] 같은 아이템 ID를 가지는 문제가 여러 개인 경우 여러 문제가 조회되는 문제 해결

- src/main/java/bgaebalja/bsherpa/security/filter/JwtCheckFilter.java
- try-catch
- exception -> jwtCustomException
- 사용하지 않는 주석처리한 코드 제거
> feat(jwt-filter): try-catch 변경 및 필터 주석 처리 제거

- src/main/java/bgaebalja/bsherpa/exam/domain/Exam.java
> fix : Exam

- src/main/java/bgaebalja/bsherpa/question/domain/GetQuestionResponse.java
> fix : GetQuestionResponse
